/*
 * Copyright (c) 2024 Vxrpenter and the SecretLab Kotlin contributors
 *
 * Licenced under the MIT License, any non-license compliant usage of this file(s) content
 * is prohibited. If you did not receive a copy of the license with this file, you
 * may obtain the license at
 *
 *  https://mit-license.org/
 *
 * This software may be used commercially if the usage is license compliant. The software
 * is provided without any sort of WARRANTY, and the authors cannot be held liable for
 * any form of claim, damages or other liabilities.
 *
 * Note: This is no legal advice, please read the license conditions
 */

package io.github.vxrpenter.ucs.uci.data

import io.github.vxrpenter.ucs.enums.secretlab.*
import io.github.vxrpenter.ucs.enums.CustomItem
import io.github.vxrpenter.ucs.enums.Role
import io.github.vxrpenter.ucs.uci.enums.EffectEvent
import io.github.vxrpenter.ucs.uci.enums.UCIItemType
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Defines the custom item's glow settings.
 */
@Serializable
data class UncomplicatedCustomItemGlowSettings(
    /**
     * The custom item's glow color (hex value).
     */
    @SerialName("glow_color")
    val glowColor: String
)

/**
 * Defines the custom item's life steal settings.
 */
@Serializable
data class UncomplicatedCustomItemLifeStealSettings(
    /**
     * The custom item's life steal amount.
     */
    @SerialName("life_steal_amount")
    val lifeStealAmount: Float,
    /**
     * The amount of health regenerated by the custom item.
     */
    @SerialName("life_steal_percentage")
    val lifeStealPercentage: Float
)

/**
 * Defines the custom item's effect settings.
 */
@Serializable
data class UncomplicatedCustomItemEffectSettings(
    /**
     * The effect event that should be triggered by the custom item.
     *
     * @see EffectEvent
     */
    @SerialName("effect_event")
    val effectEvent: EffectEvent? = null,
    /**
     * The effect applied by the custom item.
     *
     * @see EffectType
     */
    val effect: EffectType,
    /**
     * The intensity of the effect applied by the custom item.
     */
    @SerialName("effect_intensity")
    val effectIntensity: Byte,
    /**
     * The duration of the effect applied by the custom item.
     */
    @SerialName("effect_duration")
    val effectDuration: Float,
    /**
     * Defines if the duration of the effect applied by the custom item should be added to an already applied effect.
     */
    @SerialName("add_duration_if_active")
    val addDurationIfActive: Boolean? = null
)

/**
 * Defines the custom item's audio settings.
 */
@Serializable
data class UncomplicatedCustomItemAudioSettings(
    /**
     * The path of the ugg audio file.
     */
    @SerialName("audio_path")
    val audioPath: String? = null,
    /**
     * The distance the sound will be heard from.
     */
    @SerialName("audible_distance")
    val audibleDistance: Float? = null,
    /**
     * The volume the sound will be heard at
     */
    @SerialName("sound_volume")
    val soundVolume: Float? = null,
)

/**
 * Defines the custom item's explosive bullets settings.
 */
@Serializable
data class UncomplicatedCustomItemExplosiveBulletsSettings(
    /**
     * The radius the explosive bullet will apply damage at.
     */
    @SerialName("damage_radius")
    val damageRadius: Float? = null
)

/**
 * Defines the custom item's spawn item when detonated settings.
 */
@Serializable
data class UncomplicatedCustomItemSpawnItemWhenDetonatedSettings(
    /**
     * The type of item to be spawned on detonation
     */
    @SerialName("item_type")
    val itemType: CustomItem? = null,
    /**
     * The id of the item to spawn.
     *
     * @see CustomItem
     */
    @SerialName("item_id")
    val itemId: Int? = null,
    /**
     * Tje time till the item despawns.
     */
    @SerialName("time_till_despawn")
    val timeTillDespawn: Float? = null,
    /**
     * The chance to spawn the item.
     * This is applied using percentages with 0 standing for 0% and 100 for 100%.
     */
    val chance: Int? = null,
    /**
     * Defines if the item can be picked up.
     */
    val pickupable: Boolean? = null
)

/**
 * Defines the custom item's cluster settings.
 */
@Serializable
data class UncomplicatedCustomItemClusterSettings(
    /**
     * The item to spawn in a cluster.
     */
    @SerialName("item_to_spawn")
    val itemToSpawn: UCIItemType,
    /**
     * The number of items to spawn.
     */
    @SerialName("amount_to_spawn")
    val amountToSpawn: Int? = null,
    /**
     * The damage multiplier applied (if the item is e.g., a grenade)
     */
    @SerialName("scp_damage_multiplier")
    val scpDamageMultiplier: Float? = null,
    /**
     * The fuse time (if the item is e.g., a grenade)
     */
    @SerialName("fuse_time")
    val fuseTime: Float? = null
)

/**
 * Defines the custom item's switch role on use settings.
 */
@Serializable
data class UncomplicatedCustomItemSwitchRoleOnUseSettings(
    /**
     * The delay to switch roles after using the custom item.
     */
    val delay: Float? = null,
    /**
     * The type of role to switch over after using the custom item.
     *
     * @see Role
     */
    @SerialName("role_type")
    val roleType: Role? = null,
    /**
     * The id of the role to switch over after using the custom item.
     */
    @SerialName("role_id")
    val roleId: Int? = null,
    /**
     * The way the role will be spawned. This can only be used if the [roleType] is set to [Role.NORMAL].
     *
     * @see RoleSpawnFlags
     */
    @SerialName("spawn_flags")
    val spawnFlags: RoleSpawnFlags? = null,
    /**
     * Defines if the role should be spawned at the exact same position as the item's holder currently is.
     * This only works if [roleType] is [Role.ECR] or [Role.UCR]
     */
    @SerialName("keep_location")
    val keepLocation: Boolean? = null
)

/**
 * Defines the custom item's die on drop settings.
 */
@Serializable
data class UncomplicatedCustomItemDieOnDropSettings(
    /**
     * The message to display on death.
     */
    @SerialName("death_message")
    val deathMessage: String? = null,
    /**
     * Defines if the custom item's holder should be vaporized.
     */
    val vaporize: Boolean? = null
)

/**
 * Defines the custom item's can't drop settings.
 */
@Serializable
data class UncomplicatedCustomItemCantDropSettings(
    /**
     * Defines if a hint or broadcast should be displayed.
     */
    @SerialName("hint_or_broadcast")
    val hintOrBroadcast: String? = null,
    /**
     * The message to be displayed.
     */
    val message: String? = null,
    /**
     * The duration to display the message for.
     */
    val duration: Short? = null
)

/**
 * Defines the custom item's disguise settings.
 */
@Serializable
data class UncomplicatedCustomItemDisguiseSettings(
    /**
     * The type of role to disguise as.
     *
     * @see RoleType
     */
    @SerialName("role_id")
    val roleId: RoleType? = null,
    /**
     * The message sent when disguise is activated.
     */
    @SerialName("disguise_message")
    val disguiseMessage: String? = null
)

/**
 * Defines the custom item's craftable settings.
 */
@Serializable
data class UncomplicatedCustomItemCraftableSettings(
    /**
     * The Scp914 knop setting to craft the custom item at.
     *
     * @see Scp914KnobSetting
     */
    @SerialName("knob_setting")
    val knobSetting: Scp914KnobSetting? = null,
    /**
     * The item the custom item will originate from.
     */
    @SerialName("original_item")
    val originalItem: UCIItemType? = null,
    /**
     * The chance that the [originalItem] will be turned into the custom item.
     * This is applied using percentages with 0 standing for 0% and 100 for 100%.
     */
    val chance: Int? = null
)

/**
 * Defines the custom item's die on use settings.
 */
@Serializable
data class UncomplicatedCustomItemDieOnUseSettings(
    /**
     * The message to display on death.
     */
    @SerialName("death_message")
    val deathMessage: String? = null,
    /**
     * Defines if the custom item's holder should be vaporized.
     */
    val vaporize: Boolean? = null
)

/**
 * Defines the custom item's heal on kill settings.
 */
@Serializable
data class UncomplicatedCustomItemHealOnKillSettings(
    /**
     * The amount to heal the item's holder by.
     */
    @SerialName("heal_amount")
    val healAmount: Float? = null,
    /**
     * Defines if the heal amount should be converted to ahp if health is full.
     */
    @SerialName("convert_to_ahp_if_full")
    val convertToAhpIfFull: Boolean? = null
)